###################
# ANSIBLE globals #
###################

ansible_connection: local

#####################
# ENV-specific vars #
#####################

env: "stage"

#################
# ROLES globals #
#################

region: "us-west-2"

# (THIS) eks_cluster_name: used for EKS service to set an exactly cluster's name - "{{ eks_cluster_name }}"
# (AUTO) eks_cluster_stack_name: used for CloudFormation service to format a stack's name as "eksctl-{{ eks_cluster_name }}-cluster"
# (AUTO) eks_nodegroup_stack_name: used for CloudFormation service to format a stack's name as "eksctl-{{ eks_cluster_name }}-nodegroup-{{ worker-nodes-name }}"
eks_cluster_name: "{{ env }}-cluster"

# used by the cloudformation role to start a stack's name
cf_stack_name: "eksctl-{{ eks_cluster_name }}-stack"

####################
# ROLES definition #
####################

# cloudforation role
vpc_cidr_block: "10.0.0.0/16"

# eksctl role
k8s_version: 1.16
# k8s_worker_nodes_group_name: "worker-nodes"
# k8s_worker_nodes_instance_type: "t3.medium"
# k8s_worker_nodes_capacity: 2

# eks_root_user_name: "eks-root"
# eks_root_user_arn: "arn:aws:iam::<ACCOUNT-ID>:user/eks-root"
